[project]
name = "import-tax-calc"
version = "0"
description = "Import Tax Calculator for Ukraine"
readme = "README.md"
requires-python = "==3.14.*"
dependencies = [
    "django",
    "django-cors-headers",
    "djangorestframework",
    "gunicorn",
    "psycopg[binary,pool]",
]

[dependency-groups]
dev = [
    "djangorestframework-stubs",
    "pytest",
]
