# Generated by Django 5.0.4 on 2024-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tax_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro_to_usd', models.DecimalField(decimal_places=2, default=1.18, max_digits=6)),
            ],
        ),
    ]
