# Generated by Django 5.0.4 on 2024-04-15 09:59

import import_tax_calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_tax_calculator', '0001_initial_squashed_0002_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importunit',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default=import_tax_calculator.models.Currency['EUR'], max_length=3, verbose_name='EnumType'),
        ),
    ]
