# Generated by Django 5.0.4 on 2024-04-15 09:59

from django.db import migrations, models


def get_currency_eur():
    from apps.import_tax_calculator.models import Currency
    return Currency.EUR


class Migration(migrations.Migration):

    dependencies = [
        ('import_tax_calculator', '0001_initial_squashed_0002_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importunit',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default=get_currency_eur, max_length=3, verbose_name='EnumType'),
        ),
    ]
