# Generated by Django 5.0.4 on 2024-04-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('import_tax_calculator', '0001_initial'), ('import_tax_calculator', '0002_exchangerate')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='Limit for customs clearance')),
                ('duty_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=4, verbose_name='Duty rate')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.2, max_digits=4, verbose_name='VAT rate')),
            ],
        ),
        migrations.CreateModel(
            name='ImportUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', max_length=3, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euro_to_usd', models.DecimalField(decimal_places=2, default=1.07, max_digits=6)),
            ],
        ),
    ]
